# A generic, single-database configuration for Alembic

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to use for slug part of rename
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded with relative paths
# prepend_sys_path = true

# version location specification; this defaults
# to migrations/versions.  when using multiple version
# directories, paths must be separated by semicolons
# version_locations = %(here)s/bar:%(here)s/bat;migrations/versions

# version_path_separator = :

# set to 'true' to search for locations recursively
# recursive_version_locations = false

# the output encoding used when writing new migration files
# output_encoding = utf-8

sqlalchemy.url = postgresql://edutwin_admin:secure_password_here@localhost:5432/edutwin_db

[post_write_hooks]
# post_write_hooks defines scripts or tools that run after a revision is created.
# example: formatting python scripts
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
